In [2]:
import numpy as np

### Vector (1-D Array)

In [31]:
v1 = np.array([1, 2, 3])
v2 = np.array([1, 2, 3])
print(f"Vector 1 {v1.shape}: {v1}")
print(f"Vector 2 {v2.shape}: {v2}")

Vector 1 (3,): [1 2 3]
Vector 2 (3,): [1 2 3]


In [35]:
dot = np.dot(v1, v2)
print(f"Dot product: {dot}")
multiply = v1 * v2
print(f"Multiply: {multiply}")
divide = v1 / v2
print(f"Divide: {divide}")
sum = v1 + v2
print(f"Sum: {sum}")
minus = v1 - v2
print(f"Minus: {minus}")

Dot product: 14
Multiply: [1 4 9]
Divide: [1. 1. 1.]
Sum: [2 4 6]
Minus: [0 0 0]


### Matrix (2-D Array)

In [51]:
m1 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8]])
m2 = np.array([[1, 2],
               [3, 4],
               [5, 6],
               [7, 8]])
print(f"Matrix 1 {m1.shape}: {m1}")
print(f"Matrix 2 {m2.shape}: {m2}")

Matrix 1 (2, 4): [[1 2 3 4]
 [5 6 7 8]]
Matrix 2 (4, 2): [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [53]:
dot = np.dot(m1, m2)
print(f"Dot product: {dot}")

Dot product: [[ 50  60]
 [114 140]]


### Vector (1-D Array) vs Matrix (2-D Array)

In [62]:
matrix = np.array([[1, 2, 3, 4],
                   [4, 5, 6, 7],
                   [7, 8, 9, 10]])
vector = np.array([1, 2, 3])
vector = vector.reshape(3, 1)
print(f"matrix {matrix.shape}:\n{matrix}")
print(f"vector {vector.shape}: {vector}")
#dot = np.dot(matrix, vector)
#print(f"Dot product: {dot}")
multiply = matrix * vector
print(f"Multiply: {multiply}") 

matrix (3, 4):
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
vector (3, 1): [[1]
 [2]
 [3]]
Multiply: [[ 1  2  3  4]
 [ 8 10 12 14]
 [21 24 27 30]]


### Without Vectorization

In [11]:
f = 0
w = np.array([0.1, 0.2, 0.3])
x = np.array([1.0, 2.0, 3.0])
b = 5
n = x.shape[0]
for i in range(n):
    f += w[i] * x[i]
f += b
print(f)

6.4


### Vectorization

In [1]:
import numpy as np

In [12]:
w = np.array([0.1, 0.2, 0.3])
x = np.array([1.0, 2.0, 3.0])
b = 5
f = np.dot(w, x) + b
f

np.float64(6.4)